# Indexes in Pandas — Set, Reset and Use

The **index** is the label of each row. By default it is `0, 1, 2, ...`, but any
column can become the index.

You will learn:

- `df.index` — what the current labels are
- `set_index()` — make a column the row label
- `reset_index()` — turn the index back into a normal column
- `inplace=True` vs reassigning `df = ...`
- Why a meaningful index makes `.loc` lookups readable

In [1]:
# 1️⃣ Import Pandas Library
# Import pandas to work with DataFrames
import pandas as pd

In [2]:
# 2️⃣ Create a Sample DataFrame
# We will create a DataFrame with columns 'Name', 'Age', 'City'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar']
}

df = pd.DataFrame(data)  # Create DataFrame
df

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [3]:
# 3️⃣ Default Index
# By default, Pandas assigns a numeric index starting from 0
print(df.index)  # Shows the default index

RangeIndex(start=0, stop=4, step=1)

# 4️⃣ Set a Column as Index

In [4]:
df.set_index("Name")

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

### 5. Making the change permanent

`set_index()` returns a **new** DataFrame and leaves the original alone.
To keep the change you either reassign (`df = df.set_index("Name")`) or pass
`inplace=True`.

In [5]:
df.set_index("Name",inplace=True)

In [6]:
df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [7]:
# 6️⃣ Reset Index

df.reset_index()

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [8]:
# 6️⃣ Reset Index

df.reset_index(inplace=True)

### What does inplace=True mean?

- `inplace=True` means **modify the original DataFrame**
- No new DataFrame is created
- Changes happen **permanently**

### Example:
Without inplace:
```python
new_df = df.set_index("Student_ID")

In [9]:
import pandas as pd
# Creating a simple DataFrame
data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

# Display the DataFrame
df

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92

In [10]:
df.set_index("Student_ID")

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

In [11]:
df.set_index("Student_ID", inplace=True)

In [12]:
df

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

---

## Task — create your own data and practise the whole cycle

> *Original note: "create a one data and practice all like make index reset test with inplace"*

Below: build a small DataFrame, set an index without `inplace`, set it **with**
`inplace`, look rows up by label, then reset it back.

In [13]:
import pandas as pd

# A small table of shops
shops = pd.DataFrame({
    "ShopID": ["S01", "S02", "S03", "S04"],
    "Owner":  ["Anita", "Bibek", "Chandra", "Dipesh"],
    "City":   ["Kathmandu", "Pokhara", "Butwal", "Dharan"],
    "Sales":  [120000, 98000, 143000, 76000]
})
shops

  ShopID    Owner       City   Sales
0    S01    Anita  Kathmandu  120000
1    S02    Bibek    Pokhara   98000
2    S03  Chandra     Butwal  143000
3    S04   Dipesh     Dharan   76000

In [14]:
# Step 1 — the default index is RangeIndex 0,1,2,3
shops.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
# Step 2 — set_index WITHOUT inplace: returns a new DataFrame
shops.set_index("ShopID")

          Owner       City   Sales
ShopID
S01       Anita  Kathmandu  120000
S02       Bibek    Pokhara   98000
S03     Chandra     Butwal  143000
S04      Dipesh     Dharan   76000

In [16]:
# ...and the original is untouched, the index is still 0,1,2,3
shops.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
# Step 3 — now do it permanently with inplace=True
shops.set_index("ShopID", inplace=True)
shops

          Owner       City   Sales
ShopID
S01       Anita  Kathmandu  120000
S02       Bibek    Pokhara   98000
S03     Chandra     Butwal  143000
S04      Dipesh     Dharan   76000

In [18]:
# Step 4 — the labels are now the shop ids, so .loc reads like plain English
shops.loc["S03"]

Owner    Chandra
City      Butwal
Sales     143000
Name: S03, dtype: object

In [19]:
# One value: .loc[row_label, column_label]
shops.loc["S03", "Owner"]

'Chandra'

In [20]:
# Several labels at once
shops.loc[["S01", "S04"], ["Owner", "Sales"]]

         Owner   Sales
ShopID
S01      Anita  120000
S04     Dipesh   76000

In [21]:
# .iloc still works — it ignores the labels and counts POSITIONS
print("Position 0 label:", shops.iloc[0].name)
shops.iloc[0]

Position 0 label: S01

Owner        Anita
City     Kathmandu
Sales       120000
Name: S01, dtype: object

In [22]:
# Step 5 — reset_index() puts ShopID back as a normal column
shops.reset_index(inplace=True)
shops

  ShopID    Owner       City   Sales
0    S01    Anita  Kathmandu  120000
1    S02    Bibek    Pokhara   98000
2    S03  Chandra     Butwal  143000
3    S04   Dipesh     Dharan   76000

In [23]:
# reset_index(drop=True) throws the old index away instead of keeping it.
# Handy after filtering, when the leftover index has gaps like 3, 7, 12.
filtered = shops.loc[shops["Sales"] > 90000]
print("Index after filtering:", list(filtered.index))
filtered = filtered.reset_index(drop=True)
print("Index after reset_index(drop=True):", list(filtered.index))
filtered

Index after filtering: [0, 1, 2]
Index after reset_index(drop=True): [0, 1, 2]

  ShopID    Owner       City   Sales
0    S01    Anita  Kathmandu  120000
1    S02    Bibek    Pokhara   98000
2    S03  Chandra     Butwal  143000

### Key takeaways

| Goal | Code |
|------|------|
| See the current labels | `df.index` |
| Make a column the index | `df.set_index("col")` |
| Keep that change | `inplace=True` or `df = df.set_index("col")` |
| Look a row up by label | `df.loc["S03"]` |
| Look a row up by position | `df.iloc[0]` |
| Index back to a column | `df.reset_index()` |
| Renumber and discard the old index | `df.reset_index(drop=True)` |