# Pandas Data Selection — `[ ]`, `.loc`, `.iloc`
**Prepared by Ananda Rimal** · Dataset: Titanic

In this notebook we learn the 3 ways to select data from a DataFrame:

| Method | Selects by | Example |
|--------|-----------|---------|
| `df["col"]` | column name | `df["Age"]` |
| `df.loc[...]` | **labels** (names) | `df.loc[0:4, ["Name","Age"]]` |
| `df.iloc[...]` | **positions** (numbers) | `df.iloc[0:5, 0:3]` |

In [1]:
import pandas as pd

df = pd.read_csv("../data/titanic_dataset.csv")   # change the path if needed
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df.shape

(1309, 12)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [4]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1309.000000,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000
mean,655.000000,0.377387,2.294882,29.881138,0.498854,0.385027,33.295479
std,378.020061,0.484918,0.837836,14.413493,1.041658,0.865560,51.758668
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200

## 1. Selecting Columns

In [5]:
# Single column -> returns a SERIES (1 column)
df["Age"]

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ...
1304     NaN
1305    39.0
1306    38.5
1307     NaN
1308     NaN
Name: Age, Length: 1309, dtype: float64

In [6]:
# List of columns -> returns a DATAFRAME (note the double brackets!)
df[["Name", "Sex", "Age"]]

                                                   Name     Sex   Age
0                               Braund, Mr. Owen Harris    male  22.0
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                                Heikkinen, Miss. Laina  female  26.0
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                              Allen, Mr. William Henry    male  35.0
...                                                 ...     ...   ...
1304                                 Spector, Mr. Woolf    male   NaN
1305                       Oliva y Ocana, Dona. Fermina  female  39.0
1306                       Saether, Mr. Simon Sivertsen    male  38.5
1307                                Ware, Mr. Frederick    male   NaN
1308                           Peter, Master. Michael J    male   NaN

[1309 rows x 3 columns]

## 2. `.loc` — Label-based Selection (VERY IMPORTANT)

Syntax: `df.loc[row_label, column_label]`

`.loc` uses the **index labels** and column **names**.

In [7]:
# Rows with labels 0 to 4  (loc INCLUDES the end -> 5 rows!)
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
# Rows + specific columns together
df.loc[0:4, ["Name", "Age", "Sex"]]

                                                Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male

In [9]:
# One row, selected columns
df.loc[0, ["Name", "Age"]]

Name    Braund, Mr. Owen Harris
Age                        22.0
Name: 0, dtype: object

In [10]:
# ALL rows, specific columns  (the ':' means 'everything')
df.loc[:, ["Survived", "Pclass", "Fare"]]

      Survived  Pclass      Fare
0            0       3    7.2500
1            1       1   71.2833
2            1       3    7.9250
3            1       1   53.1000
4            0       3    8.0500
...        ...     ...       ...
1304         0       3    8.0500
1305         1       1  108.9000
1306         0       3    7.2500
1307         0       3    8.0500
1308         0       3   22.3583

[1309 rows x 3 columns]

## 3. `.iloc` — Position-based Selection

Syntax: `df.iloc[row_position, column_position]`

`.iloc` uses **integer positions** (0, 1, 2, ...) — like a list.

In [11]:
# First 5 rows  (iloc EXCLUDES the end -> positions 0,1,2,3,4)
df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
# Rows AND columns by position: first 5 rows, first 3 columns
df.iloc[0:5, 0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

## 4. The Key Difference: `loc` vs `iloc`

| | `.loc[0:4]` | `.iloc[0:4]` |
|---|---|---|
| Selects by | label | position |
| End included? | **YES** (5 rows) | **NO** (4 rows) |

**Tip: GENERALLY USE `.loc` INSTEAD OF `.iloc`** — labels do not change when the data is
sorted or filtered, positions do.

## 5. `set_index` — Now Labels and Positions Are DIFFERENT

Until now the index labels (0,1,2,...) happened to equal the positions, so `loc` and `iloc`
looked the same. Watch what happens when we make **PassengerId** the index.

In [13]:
df.set_index("PassengerId", inplace=True)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
# Now the index labels are 1...891 (PassengerId), but positions are still 0...890

df.loc[1]       # LABEL 1  -> passenger with PassengerId = 1  (the FIRST row)

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [15]:
df.iloc[887]    # POSITION 887 -> the 888th row (its PassengerId label is 888)

Survived                               1
Pclass                                 1
Name        Graham, Miss. Margaret Edith
Sex                               female
Age                                 19.0
SibSp                                  0
Parch                                  0
Ticket                            112053
Fare                                30.0
Cabin                                B42
Embarked                               S
Name: 888, dtype: object

In [16]:
# Same passenger, two ways:
print("By label   ->  df.loc[888]")
print("By position ->  df.iloc[887]")
df.loc[888].equals(df.iloc[887])

By label   ->  df.loc[888]
By position ->  df.iloc[887]

True

## Summary

- `df["col"]` -> one column (Series); `df[["c1","c2"]]` -> many columns (DataFrame)
- `.loc[rows, cols]` -> by **labels**, end **included**
- `.iloc[rows, cols]` -> by **positions**, end **excluded**
- After `set_index`, labels and positions become different — `.loc` follows the new index
- Prefer `.loc` in daily work

## 10 Practice Questions

*(Use the Titanic DataFrame. Q1–Q8: before `set_index`; Q9–Q10: after `set_index("PassengerId")`.)*

1. Select the `Fare` column as a Series.
2. Select the columns `Name`, `Age`, and `Survived` together in one DataFrame.
3. Select the **first 10 rows** using `.iloc`.
4. Select rows with labels **5 to 10** using `.loc`. How many rows do you get, and why?
5. Using `.loc`, select rows 0 to 4 with only the columns `Name` and `Pclass`.
6. Using `.iloc`, select the first 5 rows and the first 4 columns.
7. Using `.loc`, get the value of column `Sex` for the row with label 3.
8. Select the **last row** of the DataFrame using `.iloc` (hint: negative position).
9. After `set_index("PassengerId")`, select the passenger with **ID 100** using `.loc`.
10. Select that SAME passenger using `.iloc`. Which position number did you need, and why is it different from 100?

In [17]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
# Try your answers here

df["Fare"]

PassengerId
1         7.2500
2        71.2833
3         7.9250
4        53.1000
5         8.0500
          ...
1305      8.0500
1306    108.9000
1307      7.2500
1308      8.0500
1309     22.3583
Name: Fare, Length: 1309, dtype: float64

In [19]:
df[["Name", "Age", "Survived"]]

                                                          Name   Age  Survived
PassengerId
1                                      Braund, Mr. Owen Harris  22.0         0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
3                                       Heikkinen, Miss. Laina  26.0         1
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
5                                     Allen, Mr. William Henry  35.0         0
...                                                        ...   ...       ...
1305                                        Spector, Mr. Woolf   NaN         0
1306                              Oliva y Ocana, Dona. Fermina  39.0         1
1307                              Saether, Mr. Simon Sivertsen  38.5         0
1308                                       Ware, Mr. Frederick   NaN         0
1309                                  Peter, Master. Michael J   NaN         0

[1309 rows x 3 columns]

In [20]:
df.iloc[0:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [21]:
df.loc[5:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [22]:
df.loc[0:4, ["Name", "Pclass"]]

                                                          Name  Pclass
PassengerId
1                                      Braund, Mr. Owen Harris       3
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1
3                                       Heikkinen, Miss. Laina       3
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1

In [23]:
df.loc[3, "Sex"]

'female'

In [24]:
df.iloc[-1]

Survived                           0
Pclass                             3
Name        Peter, Master. Michael J
Sex                             male
Age                              NaN
SibSp                              1
Parch                              1
Ticket                          2668
Fare                         22.3583
Cabin                            NaN
Embarked                           C
Name: 1309, dtype: object

In [25]:
df.loc[100]

Survived                    0
Pclass                      2
Name        Kantor, Mr. Sinai
Sex                      male
Age                      34.0
SibSp                       1
Parch                       0
Ticket                 244367
Fare                     26.0
Cabin                     NaN
Embarked                    S
Name: 100, dtype: object

In [26]:
df.iloc[99]

Survived                    0
Pclass                      2
Name        Kantor, Mr. Sinai
Sex                      male
Age                      34.0
SibSp                       1
Parch                       0
Ticket                 244367
Fare                     26.0
Cabin                     NaN
Embarked                    S
Name: 100, dtype: object

### Answer Key (for the teacher)

1. `df["Fare"]`
2. `df[["Name", "Age", "Survived"]]`
3. `df.iloc[0:10]`
4. `df.loc[5:10]` -> **6 rows** (5,6,7,8,9,10) because `.loc` includes the end label
5. `df.loc[0:4, ["Name", "Pclass"]]`
6. `df.iloc[0:5, 0:4]`
7. `df.loc[3, "Sex"]`
8. `df.iloc[-1]`
9. `df.loc[100]`
10. `df.iloc[99]` -> position 99, because positions start at 0 while PassengerId labels start at 1