### Counting in Pandas

This notebook focuses only on **counting data in Pandas**.

You will learn:

- `len()`
- `count()`
- `value_counts()`
- `nunique()`
- Counting with conditions
- `groupby().count()`
- `groupby().size()`
- `pd.crosstab()`
- Titanic counting examples

### 1. Import Pandas and Create Sample Data

We will first use a small student dataset so the counting methods are easy to understand.

In [1]:
import pandas as pd

# Create sample data
data = {
    "Name": ["Anita", "Bibek", "Chandra", "Dipesh", "Elina", "Farhan"],
    "Department": ["CSIT", "BCA", "CSIT", "BIM", "BCA", "CSIT"],
    "Age": [22, 21, 23, 24, 22, 25],
    "Score": [85, 72, 91, None, 68, 77],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Butwal", "Pokhara", None]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

df

      Name Department  Age  Score       City
0    Anita       CSIT   22   85.0  Kathmandu
1    Bibek        BCA   21   72.0    Pokhara
2  Chandra       CSIT   23   91.0  Kathmandu
3   Dipesh        BIM   24    NaN     Butwal
4    Elina        BCA   22   68.0    Pokhara
5   Farhan       CSIT   25   77.0       None

### 2. Count Total Rows with `len()`

`len(df)` counts the total number of rows.

It counts a row even if some values in that row are missing.

In [2]:
# Count total number of rows
len(df)

6

### 3. Count Non-Missing Values with `count()`

`count()` counts only values that are not missing.

If a column has `NaN`, those missing values are not counted.

In [3]:
# Count non-missing Score values
df["Score"].count()

np.int64(5)

In [4]:
# QUESTION:
# Count the non-missing values in the City column.

# Write your answer below
df["City"].count()

np.int64(5)

### 4. Count Non-Missing Values in Every Column

`df.count()` returns the number of non-missing values for each column.

In [5]:
# Count non-missing values in every column
df.count()

Name          6
Department    6
Age           6
Score         5
City          5
dtype: int64

### 5. Count Values Row by Row

Use `axis=1` to count non-missing values across each row.

In [6]:
# Count non-missing values in every row
df.count(axis=1)

0    5
1    5
2    5
3    4
4    5
5    4
dtype: int64

### 6. Count Frequency with `value_counts()`

`value_counts()` tells us how many times each unique value appears.

In [7]:
# Count students in each Department
df["Department"].value_counts()

Department
CSIT    3
BCA     2
BIM     1
Name: count, dtype: int64

In [8]:
# QUESTION:
# Count how many students come from each City.

# Write your answer below
df["City"].value_counts()

City
Kathmandu    2
Pokhara      2
Butwal       1
Name: count, dtype: int64

### 7. Include Missing Values in `value_counts()`

By default, `value_counts()` ignores missing values.

Use `dropna=False` to include them.

In [9]:
# Count City values including missing values
df["City"].value_counts(dropna=False)

City
Kathmandu    2
Pokhara      2
Butwal       1
None         1
Name: count, dtype: int64

In [10]:
# QUESTION:
# Count Department values and include missing values if any.

# Write your answer below
df["Department"].value_counts(dropna=False)

Department
CSIT    3
BCA     2
BIM     1
Name: count, dtype: int64

### 8. Count Unique Values with `nunique()`

`nunique()` tells us how many different values exist.

In [11]:
# Count unique Departments
df["Department"].nunique()

3

In [12]:
# QUESTION:
# Count how many unique City values are present.

# Write your answer below
df["City"].nunique()

3

### 9. Count Rows with a Condition

A condition returns `True` or `False`.

In Pandas:

- `True` behaves like `1`
- `False` behaves like `0`

So `.sum()` can count how many rows satisfy the condition.

In [13]:
# Count students whose Score is 80 or more
(df["Score"] >= 80).sum()

np.int64(2)

In [14]:
# QUESTION:
# Count how many students are from the CSIT Department.

# Write your answer below
(df["Department"] == "CSIT").sum()

np.int64(3)

### 10. Count with Multiple Conditions

Use `&` when both conditions must be true.

In [15]:
# Count CSIT students whose Score is 80 or more
(
    (df["Department"] == "CSIT") &
    (df["Score"] >= 80)
).sum()

np.int64(2)

In [16]:
# QUESTION:
# Count students who are from Pokhara and have Age greater than 20.

# Write your answer below
(
    (df["City"] == "Pokhara") &
    (df["Age"] > 20)
).sum()

np.int64(2)

### 11. Count Groups with `groupby().count()`

`groupby().count()` counts non-missing values inside each group.

In [17]:
# Count available Score values inside each Department
df.groupby("Department")["Score"].count()

Department
BCA     2
BIM     0
CSIT    3
Name: Score, dtype: int64

In [18]:
# QUESTION:
# Count available City values inside each Department.

# Write your answer below
df.groupby("Department")["City"].count()

Department
BCA     2
BIM     1
CSIT    2
Name: City, dtype: int64

### 12. Count Total Rows per Group with `groupby().size()`

`size()` counts every row inside each group.

This is different from `count()`, because `count()` ignores missing values.

In [19]:
# Count total students in each Department
df.groupby("Department").size()

Department
BCA     2
BIM     1
CSIT    3
dtype: int64

In [20]:
# QUESTION:
# Count total rows for each City using groupby().size().

# Write your answer below
df.groupby("City").size()

City
Butwal       1
Kathmandu    2
Pokhara      2
dtype: int64

### 14. Load the Titanic Dataset

Now apply the same counting methods to the Titanic dataset.

In [21]:
# Load Titanic dataset
# Upload Titanic-Dataset.csv to Colab before running this cell
titanic = pd.read_csv("../data/titanic_dataset.csv")

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 15. Count Total Titanic Passengers

In [22]:
# Count all passenger rows
len(titanic)

1309

### 16. Count Male and Female Passengers

In [23]:
# Count passengers by Sex
titanic["Sex"].value_counts()

Sex
male      843
female    466
Name: count, dtype: int64

In [24]:
# QUESTION:
# Count how many passengers are in each Pclass.

# Write your answer below
titanic["Pclass"].value_counts()

Pclass
3    709
1    323
2    277
Name: count, dtype: int64

### 17. Count Survivors and Deaths

In the Titanic dataset:

- `1` = Survived
- `0` = Died

In [25]:
# Count survived and died passengers
titanic["Survived"].value_counts()

Survived
0    815
1    494
Name: count, dtype: int64

In [26]:
# Count only passengers who died
(titanic["Survived"] == 0).sum()

np.int64(815)

In [27]:
# Count only passengers who survived
(titanic["Survived"] == 1).sum()

np.int64(494)

### 18. Count Missing Values

Use `.isna().sum()` to count missing values in each column.

In [28]:
# Count missing values in every Titanic column
titanic.isna().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [29]:
# QUESTION:
# Count how many Age values are missing.

# Write your answer below
titanic["Age"].isna().sum()

np.int64(263)

### 19. Count Passengers by Group

Use `groupby().size()` when you want the total number of rows in each group.

In [30]:
# Count passengers by Sex
titanic.groupby("Sex").size()

Sex
female    466
male      843
dtype: int64

In [31]:
# Count passengers by Pclass and Sex
titanic.groupby(["Pclass", "Sex"]).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

### Counting Patterns to Remember

`len(df)`  
→ total rows

`df["column"].count()`  
→ non-missing values

`df["column"].value_counts()`  
→ frequency of each value

`df["column"].nunique()`  
→ number of unique values

`(condition).sum()`  
→ count rows matching a condition

`df.groupby("column").size()`  
→ total rows in each group

`df.groupby("column")["value"].count()`  
→ non-missing values inside each group

`df.isna().sum()`  
→ count missing values

`pd.crosstab(col1, col2)`  
→ frequency table

### Final Practice — 10 Titanic Counting Questions

##### Q1. Count the total number of passengers in the Titanic dataset.

##### Q2. Count how many male and female passengers are present.

##### Q3. Count how many passengers belong to each `Pclass`.

##### Q4. Count how many passengers survived and how many died.

##### Q5. Count how many passengers have missing `Age` values.

##### Q6. Count how many passengers have missing `Cabin` values.

##### Q7. Count how many passengers are male and survived.

##### Q8. Count the total number of passengers for each `Embarked` value.

##### Q9. Count passengers for every `Pclass` and `Sex` combination using `groupby().size()`.

##### Q10. Create a cross-tabulation showing `Sex` against `Survived`.

In [32]:
# Solve the 10 Titanic counting questions above here.

# count the total number of passengers in the titanic dataset
len(titanic)

1309

In [33]:
# Count how many male and female passengers are present.
titanic["Sex"].value_counts()

Sex
male      843
female    466
Name: count, dtype: int64

In [34]:
# Count how many passengers belong to each Pclass.
titanic["Pclass"].value_counts()

Pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [35]:
# Count how many passengers survived and how many died.
titanic["Survived"].value_counts()

Survived
0    815
1    494
Name: count, dtype: int64

In [36]:
# Count how many passengers have missing Age values.
titanic["Age"].isna().sum()

np.int64(263)

In [37]:
# Count how many passengers have missing Cabin values.
titanic["Pclass"].isna().sum()

np.int64(0)

In [38]:
# Count how many passengers are male and survived.
titanic.groupby(["Sex", "Survived"]).size()

Sex     Survived
female  0            81
        1           385
male    0           734
        1           109
dtype: int64

In [39]:
# Count the total number of passengers for each Embarked value.
titanic["Embarked"].value_counts()

Embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [40]:
# Count passengers for every Pclass and Sex combination using groupby().size().
titanic.groupby(["Pclass", "Sex"]).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

In [41]:
# Create a cross-tabulation showing Sex against Survived.
pd.crosstab(titanic["Sex"], titanic["Survived"])

Survived    0    1
Sex
female     81  385
male      734  109