### Pandas Series

A Series is a one-dimensional labeled array.

Think of it like:

A single column of a table

Or a vector with labels (index)

In [1]:
import pandas as pd

In [2]:
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

### Giving a Series your own index

By default a Series is labelled `0, 1, 2, ...`. Passing `index=[...]` replaces
those numbers with labels you choose, which is what makes `marks["Sita"]` possible.

In [3]:
#series with custom index
marks = pd.Series([85, 90, 88], index=["Ananda", "Sita", "Ram"])
marks

Ananda    85
Sita      90
Ram       88
dtype: int64

In [4]:
# Access by POSITION -> use .iloc
marks.iloc[0]

np.int64(85)

# Pandas DataFrame (2-D data)
What is a DataFrame?

A DataFrame is a table (rows + columns), like Excel or SQL table

In [5]:
df = pd.DataFrame({
    "Name": ["Ananda", "Sita", "Ram"],
    "Age": [22, 21, 23],
    "Score": [85, 90,85]
})

df

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

### Select Columns (very important)
#### Single column → Series
### Multiple columns → DataFrame

In [6]:
df["Age"]

0    22
1    21
2    23
Name: Age, dtype: int64

In [7]:
df[["Name", "Score"]]

     Name  Score
0  Ananda     85
1    Sita     90
2     Ram     85

In [8]:
### Now use all the general method for this dataframe like and find first 2 data last two data info and shape
df.head()

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

In [9]:
df.tail(5)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

In [10]:
df.shape

(3, 3)

In [11]:
df.head(1)

     Name  Age  Score
0  Ananda   22     85

In [12]:
df.sample()

   Name  Age  Score
1  Sita   21     90

In [13]:

df = pd.DataFrame({
    "Name": [
        "Ananda", "Sita", "Ram", "Gita", "Hari", "Nita", "Ravi", "Pooja", "Kiran", "Maya",
        "Amit", "Sneha", "Rohan", "Anita", "Bikash", "Nisha", "Rahul", "Puja", "Suman", "Kavita",
        "Arjun", "Neha", "Sagar", "Rita", "Manish", "Sunita", "Deepak", "Priya", "Rohit", "Alina",
        "Vikas", "Mina", "Nabin", "Komal", "Dipesh", "Laxmi", "Prakash", "Isha", "Niraj", "Asha",
        "Suraj", "Riya", "Santosh", "Anjali", "Hemant", "Pawan", "Monika", "Ashok", "Preeti", "Sonia"
    ],
    "Age": [
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21
    ],
    "Score": [
        85, 90, 88, 76, 92, 81, 87, 79, 84, 90,
        86, 78, 91, 83, 89, 80, 88, 82, 90, 77,
        85, 84, 92, 79, 88, 81, 90, 83, 87, 86,
        91, 78, 84, 82, 89, 80, 88, 85, 92, 77,
        90, 83, 91, 79, 86, 84, 88, 81, 90, 85
    ]
})

df

       Name  Age  Score
0    Ananda   22     85
1      Sita   21     90
2       Ram   23     88
3      Gita   20     76
4      Hari   22     92
5      Nita   21     81
6      Ravi   23     87
7     Pooja   20     79
8     Kiran   22     84
9      Maya   21     90
10     Amit   23     86
11    Sneha   20     78
12    Rohan   22     91
13    Anita   21     83
14   Bikash   23     89
15    Nisha   20     80
16    Rahul   22     88
17     Puja   21     82
18    Suman   23     90
19   Kavita   20     77
20    Arjun   22     85
21     Neha   21     84
22    Sagar   23     92
23     Rita   20     79
24   Manish   22     88
25   Sunita   21     81
26   Deepak   23     90
27    Priya   20     83
28    Rohit   22     87
29    Alina   21     86
30    Vikas   23     91
31     Mina   20     78
32    Nabin   22     84
33    Komal   21     82
34   Dipesh   23     89
35    Laxmi   20     80
36  Prakash   22     88
37     Isha   21     85
38    Niraj   23     92
39     Asha   20     77
40    Suraj   22     90
41     Riya   21     83
42  Santosh   23     91
43   Anjali   20     79
44   Hemant   22     86
45    Pawan   21     84
46   Monika   23     88
47    Ashok   20     81
48   Preeti   22     90
49    Sonia   21     85

### Saving a DataFrame to a CSV file

`to_csv()` writes the table to disk. `index=False` stops pandas from adding an
extra unnamed `0,1,2,...` column to the file.

In [14]:
# save the generated data into local system
df.to_csv('../data/data.csv', index=False)  # index=False avoids adding row numbers

In [15]:
# apply all the analysis like info shape ,describe and others things in your data and find the first 10 and last 10 data 
df.head(10)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     88
3    Gita   20     76
4    Hari   22     92
5    Nita   21     81
6    Ravi   23     87
7   Pooja   20     79
8   Kiran   22     84
9    Maya   21     90

In [16]:
df.sample()

     Name  Age  Score
27  Priya   20     83

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    50 non-null     object
 1   Age     50 non-null     int64
 2   Score   50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [18]:
df.describe()

             Age      Score
count  50.000000  50.000000
mean   21.500000  85.080000
std     1.111168   4.606296
min    20.000000  76.000000
25%    21.000000  81.250000
50%    21.500000  85.000000
75%    22.000000  89.000000
max    23.000000  92.000000

In [19]:
import pandas as pd
import random

# Seed the generator so this notebook produces the SAME file every time it runs
random.seed(42)

names = [
    "Ram", "Shyam", "Hari", "Sita", "Gita", "Ramesh", "Suresh",
    "Bikash", "Prakash", "Anil", "Sunil", "Aashish", "Bibek",
    "Nabin", "Suman", "Kiran", "Sabin", "Roshan", "Manish", "Dipesh"
]

fields = ["IT", "Medicine", "Engineer", "Business", "Finance", "Education"]

cities = [
    "Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Chitwan",
    "Biratnagar", "Dharan", "Butwal", "Janakpur", "Nepalgunj"
]

data = {
    "Name": [random.choice(names) for _ in range(1000)],
    "Salary": [random.randint(20000, 150000) for _ in range(1000)],
    "Field": [random.choice(fields) for _ in range(1000)],
    "Age": [random.randint(20, 60) for _ in range(1000)],
    "City": [random.choice(cities) for _ in range(1000)]
}

df = pd.DataFrame(data)

df

        Name  Salary      Field  Age        City
0       Sita   57072  Education   42   Kathmandu
1        Ram  115164    Finance   29   Bhaktapur
2    Prakash   59132         IT   37    Janakpur
3     Bikash  129769  Education   32  Biratnagar
4     Bikash   96931  Education   27   Kathmandu
..       ...     ...        ...  ...         ...
995    Nabin  107833    Finance   54   Kathmandu
996    Sunil  112121   Business   35   Nepalgunj
997    Sabin  128653   Medicine   29     Pokhara
998  Prakash  144139   Medicine   20      Butwal
999      Ram  116832   Business   46      Butwal

[1000 rows x 5 columns]

In [20]:
df.to_csv("../data/nepali_data.csv", index=False)

### Reading the file back

A good habit after saving: read the file again and confirm it looks the way you expect.

In [21]:
# Read the file we just wrote
check = pd.read_csv("../data/nepali_data.csv")
print(check.shape)
check.head()

(1000, 5)

      Name  Salary      Field  Age        City
0     Sita   57072  Education   42   Kathmandu
1      Ram  115164    Finance   29   Bhaktapur
2  Prakash   59132         IT   37    Janakpur
3   Bikash  129769  Education   32  Biratnagar
4   Bikash   96931  Education   27   Kathmandu

In [22]:
# Series vs DataFrame, one last time, on this data
one_column = check["Salary"]          # single brackets -> Series
two_columns = check[["Name", "Salary"]]  # double brackets -> DataFrame

print(type(one_column))
print(type(two_columns))
one_column.head()

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

0     57072
1    115164
2     59132
3    129769
4     96931
Name: Salary, dtype: int64

In [23]:
# A Series carries its own index and knows its own statistics
print("mean  :", round(check["Salary"].mean(), 2))
print("max   :", check["Salary"].max())
print("min   :", check["Salary"].min())
check["Salary"].describe()

mean  : 85886.98
max   : 149890
min   : 20371

count      1000.000000
mean      85886.977000
std       36965.875349
min       20371.000000
25%       55936.500000
50%       86085.500000
75%      117451.500000
max      149890.000000
Name: Salary, dtype: float64

### Key takeaways

| Concept | Shape | Made with |
|---------|-------|-----------|
| **Series** | 1-D — one labelled column | `pd.Series([...])`, `df["col"]` |
| **DataFrame** | 2-D — a whole table | `pd.DataFrame({...})`, `df[["col"]]` |

| Goal | Code |
|------|------|
| Build a table from a dict | `pd.DataFrame({"A": [...], "B": [...]})` |
| Save it | `df.to_csv("../data/file.csv", index=False)` |
| Load it back | `pd.read_csv("../data/file.csv")` |

### you can add your own note below using pandas offical documentation https://pandas.pydata.org/docs/

---

## Task — detailed comparison between Series and DataFrame

> *Original note: "find and write the detailed comparison between Series and DataFrame with code example"*

| | **Series** | **DataFrame** |
|---|---|---|
| Dimensions | 1-D | 2-D |
| Think of it as | one column | a whole table |
| Axes | one index | an index **and** columns |
| `.shape` | `(n,)` | `(rows, cols)` |
| dtype | one dtype for the whole Series | one dtype **per column** |
| Built from | a list, a dict, `df["col"]` | a dict of lists, a list of dicts, `df[["col"]]` |
| Has `.columns`? | no | yes |
| `.name` | the column's name | not applicable |
| A single column of it | `s.iloc[0]` → one value | `df["col"]` → a Series |
| Common use | one variable, one measurement | the dataset itself |

**The link between them:** a DataFrame is a collection of Series that share one index.
Pull a column out and you get a Series; put Series back together and you get a
DataFrame.

In [24]:
import pandas as pd

# The SAME data, once as a Series and once as a DataFrame
scores_series = pd.Series([85, 90, 88], index=["Ananda", "Sita", "Ram"], name="Score")
scores_frame  = pd.DataFrame({"Score": [85, 90, 88]}, index=["Ananda", "Sita", "Ram"])

print("SERIES"); print(scores_series)
print()
print("DATAFRAME"); print(scores_frame)

SERIES
Ananda    85
Sita      90
Ram       88
Name: Score, dtype: int64

DATAFRAME
        Score
Ananda     85
Sita       90
Ram        88

In [25]:
# 1. Type and shape
print("type :", type(scores_series).__name__, "|", type(scores_frame).__name__)
print("shape:", scores_series.shape, "     |", scores_frame.shape)
print("ndim :", scores_series.ndim, "              |", scores_frame.ndim)

type : Series | DataFrame
shape: (3,)      | (3, 1)
ndim : 1               | 2

In [26]:
# 2. A Series has a .name, a DataFrame has .columns
print("Series .name    :", scores_series.name)
print("DataFrame .columns:", list(scores_frame.columns))

Series .name    : Score
DataFrame .columns: ['Score']

In [27]:
# 3. Selecting one element
print("Series by label   :", scores_series["Sita"])
print("Series by position:", scores_series.iloc[1])
print("DataFrame needs BOTH row and column:", scores_frame.loc["Sita", "Score"])

Series by label   : 90
Series by position: 90
DataFrame needs BOTH row and column: 90

In [28]:
# 4. dtypes: one for a Series, one PER COLUMN for a DataFrame
mixed = pd.DataFrame({
    "Name":  ["Ananda", "Sita", "Ram"],
    "Age":   [22, 21, 23],
    "Score": [85.5, 90.0, 88.5]
})
print("Series dtype :", scores_series.dtype)
print()
print("DataFrame dtypes:")
print(mixed.dtypes)

Series dtype : int64

DataFrame dtypes:
Name      object
Age        int64
Score    float64
dtype: object

In [29]:
# 5. Going back and forth
col = mixed["Age"]                 # DataFrame -> Series
back = col.to_frame()              # Series -> DataFrame
rebuilt = pd.DataFrame({"Age": mixed["Age"], "Score": mixed["Score"]})  # Series -> DataFrame

print(type(col).__name__, "->", type(back).__name__)
rebuilt

Series -> DataFrame

   Age  Score
0   22   85.5
1   21   90.0
2   23   88.5

In [30]:
# 6. The same method behaves differently on each
print("Series.describe() — one summary:")
print(scores_series.describe())
print()
print("DataFrame.describe() — one summary PER numeric column:")
print(mixed.describe())

Series.describe() — one summary:
count     3.000000
mean     87.666667
std       2.516611
min      85.000000
25%      86.500000
50%      88.000000
75%      89.000000
max      90.000000
Name: Score, dtype: float64

DataFrame.describe() — one summary PER numeric column:
        Age      Score
count   3.0   3.000000
mean   22.0  88.000000
std     1.0   2.291288
min    21.0  85.500000
25%    21.5  87.000000
50%    22.0  88.500000
75%    22.5  89.250000
max    23.0  90.000000

### Key takeaways

- `df["col"]` → **Series** · `df[["col"]]` → **DataFrame** (one column, still a table)
- A DataFrame is just Series glued together on a shared index
- A Series has one dtype; a DataFrame has one per column
- Selecting from a Series needs **one** key; from a DataFrame, a row **and** a column