In [1]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Age": [22, 19, 25, 21],
    "Marks": [78, 85, 67, 90]
}

df = pd.DataFrame(data)
df

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [2]:
df.head(3)

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67

In [3]:
df.tail(3)

   Name  Age  Marks
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [4]:
#Sort by Age
df.sort_values(by="Age")

   Name  Age  Marks
1  Sita   19     85
3  Gita   21     90
0   Ram   22     78
2  Hari   25     67

In [5]:
# Sort by Marks
df.sort_values(by="Marks")

   Name  Age  Marks
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85
3  Gita   21     90

In [6]:
# First by Age, then by Marks
df.sort_values(by=["Age", "Marks"])

   Name  Age  Marks
1  Sita   19     85
3  Gita   21     90
0   Ram   22     78
2  Hari   25     67

In [7]:
df.sort_values(by=["Age", "Marks"], ascending=[True, False])
# Different order for each column:

   Name  Age  Marks
1  Sita   19     85
3  Gita   21     90
0   Ram   22     78
2  Hari   25     67

In [8]:
df.sort_index()
# sort by index

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [9]:
df.sort_index(ascending=False)

   Name  Age  Marks
3  Gita   21     90
2  Hari   25     67
1  Sita   19     85
0   Ram   22     78

In [10]:
df

   Name  Age  Marks
0   Ram   22     78
1  Sita   19     85
2  Hari   25     67
3  Gita   21     90

In [11]:
# Sort and save changes (inplace)
df.sort_values(by="Marks", inplace=True)
df

   Name  Age  Marks
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85
3  Gita   21     90

In [12]:
df

   Name  Age  Marks
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85
3  Gita   21     90

In [13]:
# Sort strings (alphabetical order)
df.sort_values(by="Name")

   Name  Age  Marks
3  Gita   21     90
2  Hari   25     67
0   Ram   22     78
1  Sita   19     85

In [14]:
# Reverse alphabetical:
df.sort_values(by="Name", ascending=False)

   Name  Age  Marks
1  Sita   19     85
0   Ram   22     78
2  Hari   25     67
3  Gita   21     90

## 🧠 Quick Summary

| Task | Method |
|------|--------|
| Sort rows | `sort_values()` |
| Sort index | `sort_index()` |
| Descending order | `ascending=False` |
| Multiple columns | `by=[...]` |
| Save changes | `inplace=True` |
| Fix index | `reset_index(drop=True)` |

---

## Practice — sorting on a real dataset

The examples above used a 4-row table. Here are the same methods on the
1000-row `nepali_data.csv`, where sorting actually tells you something.

In [15]:
import pandas as pd

emp = pd.read_csv("../data/nepali_data.csv")
emp.head()

      Name  Salary      Field  Age        City
0     Sita   57072  Education   42   Kathmandu
1      Ram  115164    Finance   29   Bhaktapur
2  Prakash   59132         IT   37    Janakpur
3   Bikash  129769  Education   32  Biratnagar
4   Bikash   96931  Education   27   Kathmandu

In [16]:
# Highest paid first
emp.sort_values(by="Salary", ascending=False).head(10)

        Name  Salary      Field  Age        City
932   Roshan  149890   Business   23     Pokhara
426    Sunil  149606   Engineer   35   Bhaktapur
42   Prakash  149553   Business   37  Biratnagar
175  Prakash  149453    Finance   24      Butwal
452   Manish  149437         IT   22     Pokhara
856    Suman  149306    Finance   24      Dharan
726   Suresh  149033         IT   51    Janakpur
450     Sita  148978   Engineer   30    Janakpur
922    Nabin  148763  Education   53   Bhaktapur
396  Aashish  148572         IT   45  Biratnagar

In [17]:
# Lowest paid first (ascending is the default)
emp.sort_values(by="Salary").head(10)

        Name  Salary      Field  Age        City
447    Nabin   20371    Finance   26   Kathmandu
659  Prakash   20800   Engineer   33     Pokhara
729    Sunil   21007         IT   22    Lalitpur
741   Roshan   21013  Education   28  Biratnagar
205    Sunil   21061   Business   53      Butwal
162    Shyam   21231    Finance   51   Nepalgunj
308    Sunil   21824    Finance   60      Butwal
463     Hari   21947    Finance   53     Chitwan
66    Ramesh   22011    Finance   39     Chitwan
470     Anil   22068  Education   45   Nepalgunj

In [18]:
# Two columns: group the fields alphabetically, and inside each field
# put the highest salary on top.
emp.sort_values(by=["Field", "Salary"], ascending=[True, False]).head(15)

        Name  Salary     Field  Age        City
932   Roshan  149890  Business   23     Pokhara
42   Prakash  149553  Business   37  Biratnagar
47     Bibek  148557  Business   60     Pokhara
401   Bikash  148167  Business   56    Janakpur
503    Sabin  146356  Business   26   Nepalgunj
92     Sunil  145060  Business   22      Butwal
391    Shyam  144591  Business   58   Nepalgunj
350   Roshan  144028  Business   44    Janakpur
331  Aashish  143623  Business   21   Nepalgunj
275    Shyam  139806  Business   23     Pokhara
270    Kiran  139732  Business   44   Nepalgunj
213     Gita  139356  Business   37   Bhaktapur
64     Suman  139333  Business   35     Chitwan
514   Bikash  139236  Business   34    Lalitpur
255    Nabin  139226  Business   40      Dharan

In [19]:
# Sorting does NOT renumber the rows — the old index travels with them.
# reset_index(drop=True) gives a clean 0,1,2,... again.
top = emp.sort_values("Salary", ascending=False).head(5)
print("Index straight after sorting:", list(top.index))
top = top.reset_index(drop=True)
print("After reset_index(drop=True) :", list(top.index))
top

Index straight after sorting: [932, 426, 42, 175, 452]
After reset_index(drop=True) : [0, 1, 2, 3, 4]

      Name  Salary     Field  Age        City
0   Roshan  149890  Business   23     Pokhara
1    Sunil  149606  Engineer   35   Bhaktapur
2  Prakash  149553  Business   37  Biratnagar
3  Prakash  149453   Finance   24      Butwal
4   Manish  149437        IT   22     Pokhara

In [20]:
# Sorting a column that has missing values:
# by default NaN goes LAST, na_position="first" flips it.
with_gaps = emp.copy()
with_gaps.loc[0:4, "Salary"] = None

print("NaN last (default):")
print(with_gaps.sort_values("Salary")[["Name", "Salary"]].tail(3))
print()
print('NaN first (na_position="first"):')
print(with_gaps.sort_values("Salary", na_position="first")[["Name", "Salary"]].head(3))

NaN last (default):
      Name  Salary
2  Prakash     NaN
3   Bikash     NaN
4   Bikash     NaN

NaN first (na_position="first"):
      Name  Salary
0     Sita     NaN
1      Ram     NaN
2  Prakash     NaN

In [21]:
# sort_index() sorts by the ROW LABELS rather than by a column.
# Most useful right after a filter, to put the rows back in their original order.
sample = emp.sample(8, random_state=1)
print("Random order:", list(sample.index))
sample.sort_index()

Random order: [507, 818, 452, 368, 242, 929, 262, 810]

        Name  Salary     Field  Age        City
242  Prakash  138410  Business   22  Biratnagar
262    Bibek   37322        IT   39      Dharan
368    Sunil   90804  Engineer   35      Butwal
452   Manish  149437        IT   22     Pokhara
507   Bikash  131057  Medicine   31   Bhaktapur
810    Kiran   30011   Finance   47   Bhaktapur
818     Gita  121741  Business   58   Nepalgunj
929    Kiran   52472  Business   49      Butwal

In [22]:
# Sorting a groupby result is the usual way to build a "top N" table
emp.groupby("Field")["Salary"].mean().sort_values(ascending=False)

Field
Medicine     89143.827160
Education    86716.446429
Business     86287.786982
Engineer     85493.840909
IT           85081.892617
Finance      82787.272727
Name: Salary, dtype: float64